# Change these first
owner: sxbascv # Tu usuario real de GitHub
repo: Taller2GHA2 # El nombre exacto de tu repositorio

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

status-website:
  # Comenta o borra la línea cname ya que no tienes un dominio personalizado propio
  # cname: demo.upptime.js.org
  baseUrl: /Taller2GHA2 # <- Importante: debe coincidir exactamente con el nombre de tu repositorio
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
